### ISSUE TITLE
uninitialized memcache port number doesn't default properly

### ISSUE THREAD

**Issue by jrbl** [Stanford-Online/edx-platform#1]
If you leave the ```:12345``` off the end of your memcache hostname, the thing that's supposed to set it to a sensible default, doesn't. I'm not sure why. Traceback from an ansible run:

```
failed: [ip-10-0-10-247.us-west-1.compute.internal] => {"changed": true, "cmd": " SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:01:11.304751", "end": "2013-07-29 22:03:25.904776", "item": "", "rc": 1, "start": "2013-07-29 22:02:14.600025"}
stderr: ./manage.py lms --settings aws preprocess_assets --traceback 
xmodule_assets common/static/xmodule
node_modules/.bin/coffee --compile  .
sass --style compressed --load-path ./common/static/sass /opt/wwc/themes/stanford/static/sass --update -E utf-8 */static /opt/wwc/themes/stanford/static/sass
./manage.py lms --settings aws collectstatic --traceback --noinput > /dev/null
Traceback (most recent call last):
  File "./manage.py", line 90, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/opt/edx/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 169, in handle_noargs
    collected = self.collect()
  File "/opt/edx/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 126, in collect
    for original_path, processed_path, processed in processor:
  File "/opt/edx/src/django-staticfiles/staticfiles/storage.py", line 279, in post_process
    content = pattern.sub(converter, content)
  File "/opt/edx/src/django-staticfiles/staticfiles/storage.py", line 218, in converter
    hashed_url = self.url(unquote(joined_result), force=True)
  File "/opt/edx/src/django-staticfiles/staticfiles/storage.py", line 162, in url
    hashed_name = self.cache.get(cache_key)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/cache/backends/memcached.py", line 57, in get
    val = self._cache.get(key)
  File "/opt/edx/local/lib/python2.7/site-packages/django/core/cache/backends/memcached.py", line 31, in _cache
    self._client = self._lib.Client(self._servers)
  File "/opt/edx/local/lib/python2.7/site-packages/memcache.py", line 195, in __init__
    self.set_servers(servers)
  File "/opt/edx/local/lib/python2.7/site-packages/memcache.py", line 239, in set_servers
    for s in servers]
  File "/opt/edx/local/lib/python2.7/site-packages/memcache.py", line 1058, in __init__
    self.port = int(hostData.get('port', 11211))
TypeError: int() argument must be a string or a number, not 'NoneType'
collectstatic failed!
stdout: phantomjs not found on path. Set $PHANTOMJS_PATH. Using browser for jasmine tests
  overwrite lms/static/sass/application.css
  overwrite lms/static/sass/course.css

FATAL: all hosts have already failed -- aborting
```

IT may be as easy as turning that .get() call into something else; or maybe extending the underlying object definition to support the complete dict api (clearly something expects dict semantics and something else doesn't *quite* provide them.) In any case not important to do today.

**Comment by stvstnfrd** [comment]
Closed as deprecated.
